### PR TITLE
Added Email support using 'nodemailer' for email confirmation

### PR DESCRIPTION
**Pull request by nybroe**
Includes changes that allow an confirmation email to be send to any email ones the registrations has gone through and passed all tests.

The implementation and usage of the confirmation is optional.

**Usage**:
Add the following secrets/env variables to the exiciting collection of secrets:
`EMAILSMTPHOST`: the host of the smtp server that the email will be send from, ie: `smtp.mydomain.com`
`EMAILSMTPORT`: the port of the smtp server that the email will be send from, ie: `2525`
`EMAILAUTHUSER`: the username for the smtpserver login
`EMAILAUTHPASS`: the password for the smtpserver login
`FROMEMAIL`: the email you want the recipient to see
`TOEMAILS`: a comma sperated string (no spaces) of emails you want the mail to be send to. ie: `me@email.com,your@email.com`

If the `EMAILSMTPHOST `variable is left empty, no email will be send and it wont break the testflow.

**Remember** to run a new `npm install` to include the `nodemailer` package

### CODE REVIEW

**Comment by simplenotezy** [comment]
Cool idea, I like it.

I would like to note I'd prefer some underscore between the environment variables to make them more readable, like, EMAIL_SENDER, EMAIL_TO, etc, but given the nature of the (hopefully) relatively small life of this repo, I'll accept it as is.

Great work, and thanks!

**Comment by nybroe** [comment]
@simplenotezy I agree that this would be the best way and easier to read. 
Since I had some issues myself using secrets and env variable with `Github Actions` I choosed to not split the word with underscore. This was done to avoid any conflict with the way env variables are handled with underscore - AND because of this only being a small side project, I got lazy - to be honest..

**Comment by simplenotezy** [comment]
Hehe, you're forgiven.  Again, nice addition.

**Comment by saulhardman** [comment]
@nybroe just to let you know [the commit history](https://github.com/simplenotezy/order-surplus-vaccine/pull/1/commits/853e769d4d18d4e197715dad2ca543d2f37a1b41#diff-fe431734a176f59ad0819519d3c2eebcba59dc7de9371bffb896474f1b2fd5e7R22) leaks your personal account details for `simply.com` webmail (email and password). I'd recommend updating your password as soon as possible and being a little more careful about committing sensitive information to public Git repositories in the future.

**Comment by nybroe** [comment]
@saulhardman This is just a test server but exposing credentials in code is just a no-go. Thanks. :)

**Pull request merged**
